import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} m-4`}>
        <nav className="flex gap-4">
          <Link href="/">Home</Link>

          {Array.from(Array(10).keys()).map((i) => (
            <Link key={i} href={`/post/${i}`}>
              Post {i}
            </Link>
          ))}
        </nav>

        <main className="mt-8">{children}</main>
      </body>
    </html>
  );
}
